---
- name: deploy tomcat8 based application game of life
  become: yes
  hosts: localhost
  tasks:
    - name: update apt packages and install java
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: install tomcat9
      apt: 
        name: tomcat9
        state: present
    - name: Download game of life
      get_url:
        url: https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
        dest: /var/lib/tomcat9/webapps/gameoflife.war